#!/bin/bash


kill_pid()
{
  if test -e "$1"
  then
    kill `cat "$1"` 2>/dev/null
  fi
}

cleanup()
{
  kill_pid /tmp/tracker/pid
  kill_pid /tmp/1/pid
  kill_pid /tmp/2/pid

  sleep 0.1
  kill_pid /tmp/testing/Tracker
  kill_pid "/tmp/testing/Daemon-Client"
  kill_pid "/tmp/testing/Daemon-Server"

  rm -rf /tmp/1 /tmp/2 /tmp/tracker /tmp/testing
}

ctrl_c()
{
  cleanup
  exit 1
}

run_program()
{
  mkdir -p /tmp/testing
  tempfile=/tmp/testing/`echo "$1" | tr ' ' '-'`

  gnome-terminal --title "$1" -e "bash -c '($2; sleep 600) & echo \$! > $tempfile; wait \$!'" &
}

wait_file()
{
  echo "Waiting for '$2' in $1"
  while ! test -e /tmp/$1/stuff/$2
  do
    sleep 1
  done
}

metadata()
{
  stat $1 | egrep -v '^\ *(File:|Device:|Access: 2|Change:)'
}

verify_synced()
{
  wait_file 1 $1
  wait_file 2 $1
  if ! cmp /tmp/{1,2}/stuff/$1
  then
    echo "$1 doesn't match"
    sleep 2
    cleanup
    exit -1
  fi

  if ! diff -u <(metadata /tmp/1/stuff/$1) <(metadata /tmp/2/stuff/$1)
  then
    echo "metadata for '$1' doesn't match"
    sleep 10
    cleanup
    exit -1
  fi
}

wait_gone()
{
  echo "Waiting for $1 to be deleted"
  while test -e "$1"
  do
    sleep 1
  done
}


trap ctrl_c SIGINT

cleanup

mkdir -p /tmp/tracker
run_program "Tracker" "PIDFILE=/tmp/tracker/pid tracker/server"

mkdir -p /tmp/1/stuff
echo my first file > /tmp/1/stuff/first
echo my second file > /tmp/1/stuff/second
echo my read-only file > /tmp/1/stuff/read-only
chmod 400 /tmp/1/stuff/read-only

# ----- Server -----

run_program "Daemon Server" "CLEARSKIES_DIR=/tmp/1 ./clearskies debug"

echo "Waiting for server to start"
while ! test -e /tmp/1/control
do
  sleep 0.1
done

echo "Creating share on server"
echo "Requesting access code from server"
code=$(CLEARSKIES_DIR=/tmp/1 ./clearskies share /tmp/1/stuff read_write)
echo "Code is '$code'"

# ----- Client -----

run_program "Daemon Client" "CLEARSKIES_DIR=/tmp/2 ./clearskies debug"

echo "Waiting for client to start"
while ! test -e /tmp/2/control
do
  sleep 0.1
done

echo "Adding access code to client"
CLEARSKIES_DIR=/tmp/2 ./clearskies add "$code" /tmp/2/stuff

# ----- Initial Sync ------

verify_synced first
verify_synced second
verify_synced read-only

# ----- Change a file -----

echo "This is still the first file" > /tmp/1/stuff/first

# ----- Create files on client -----

echo "A wild file appears!" > /tmp/2/stuff/third
echo "with a friend" > /tmp/2/stuff/fourth

verify_synced third
verify_synced fourth

# ----- Delete a file -----

rm /tmp/1/stuff/fourth

wait_gone /tmp/2/stuff/fourth

# ----- Create subdirectory -----

mkdir /tmp/1/stuff/subdir
echo "Five files for me" > /tmp/1/stuff/subdir/five
verify_synced subdir/five

echo "Test successful!"

sleep 2

cleanup

exit 0
