#!/bin/bash

. test/integration-functions

start_session

cleanup
rm -rf /tmp/1 /tmp/2 /tmp/testing
mkdir -p /tmp/1/stuff
echo my first file > /tmp/1/stuff/first
echo my second file > /tmp/1/stuff/second
echo my read-only file > /tmp/1/stuff/read-only
chmod 400 /tmp/1/stuff/read-only

# I call the two Daemons Server and Client just for internal mental reference

# ----- Server -----

launch_daemon "Server" 1

log "Creating share on server"
log "Requesting access code from server"
code=$(CLEARSKIES_DIR=/tmp/1 ./clearskies share /tmp/1/stuff read_write)
log "Code is '$code'"

# ----- Client -----

launch_daemon "Server" 2

log "Adding access code to client"
CLEARSKIES_DIR=/tmp/2 ./clearskies add "$code" /tmp/2/stuff

# ----- Initial Sync ------

verify_synced first
verify_synced second
verify_synced read-only

# ----- Change a file -----

log "Changing first on server"
echo "This is still the first file" > /tmp/1/stuff/first

# Force delay by creating another file
log "Creating bar on server"
touch /tmp/1/stuff/bar
verify_synced bar
verify_synced first

# ----- Create files on client -----

log "Creating third and fourth on client"
echo "A wild file appears!" > /tmp/2/stuff/third
echo "with a friend" > /tmp/2/stuff/fourth

verify_synced third
verify_synced fourth

# ----- Detect metadata change -----
log "Changing mode of first on client"
chmod 600 /tmp/2/stuff/first

# Force delay by creating another file
log "Creating foo on client"
touch /tmp/2/stuff/foo
verify_synced foo
verify_synced first

# ----- Delete a file -----

log "Removing fourth"
rm /tmp/1/stuff/fourth

wait_gone /tmp/2/stuff/fourth

# ----- Create subdirectory -----

# Test that directory contents are added even if the monitor
# is not in place by the time they are created
kill -STOP `cat /tmp/1/pid`
log "Making subdir/five on server"
mkdir /tmp/1/stuff/subdir
echo "Five files for me" > /tmp/1/stuff/subdir/five
kill -CONT `cat /tmp/1/pid`

verify_synced subdir/five

# Also verify that files that appear afterward are also detected

log "Creating subdir/six on server"
echo "Now six, six files" > /tmp/1/stuff/subdir/six
verify_synced subdir/six

log "Checking all files again"
verify_synced first
verify_synced second
verify_synced read-only
verify_synced third
verify_missing fourth
verify_synced subdir/five
verify_synced subdir/six

log "Test successful!"

read foo

cleanup

exit 0
